rm()
library(readxl)
library(matrixcalc)
library(ggplot2)
library(agricolae)

path_file <- "/home/jonathan/Documents/ED/Week2/Data.xlsx"
pt <- read_excel(path = path_file, sheet = 5, range = "AT3:AT35")
tc <- read_excel(path = path_file, sheet = 5, range = "AU3:AT35")
ht <- read_excel(path = path_file, sheet = 5, range = "AV3:AV35")
gr <- read_excel(path = path_file, sheet = 5, range = "AW3:AW35")
cl <- read_excel(path = path_file, sheet = 5, range = "AX3:AX35")

df <- data.frame(pt, tc, ht, gr, cl)

# Calculating the factor effects (1)
a <- (df$Life.Hours[df$Cutting.Speed == 1 & df$Tool.Geometry == -1 & df$Cutting.Angle == -1])
ab <- (df$Life.Hours[df$Cutting.Speed == 1 & df$Tool.Geometry == 1 & df$Cutting.Angle == -1])
ac <- (df$Life.Hours[df$Cutting.Speed == 1 & df$Tool.Geometry == -1 & df$Cutting.Angle == 1])
abc <- (df$Life.Hours[df$Cutting.Speed == 1 & df$Tool.Geometry == 1 & df$Cutting.Angle == 1])
o <- (df$Life.Hours[df$Cutting.Speed == -1 & df$Tool.Geometry == -1 & df$Cutting.Angle == -1])
b <- (df$Life.Hours[df$Cutting.Speed == -1 & df$Tool.Geometry == 1 & df$Cutting.Angle == -1])
c <- (df$Life.Hours[df$Cutting.Speed == -1 & df$Tool.Geometry == -1 & df$Cutting.Angle == 1])
bc <- (df$Life.Hours[df$Cutting.Speed == -1 & df$Tool.Geometry == 1 & df$Cutting.Angle == 1])
a_plus <- sum(a + ab + ac + abc)
a_min <- sum(o + b + c + bc)
effect_a <- mean(a_plus) - mean(a_min)
b_plus <- sum(b + ab + bc + abc)
b_min <- sum(o + a + c + ac)
effect_b <- mean(b_plus) - mean(b_min)
c_plus <- sum(c + ac + bc + abc)
c_min <- sum(o + a + b + ab)
effect_c <- mean(c_plus) - mean(c_min)
ab_plus <- sum(abc + ab + c + o)
ab_min <- sum(bc + b + ac + a)
effect_ab <- mean(ab_plus) - mean(ab_min)
ac_plus <- sum(o + b + ac + abc)
ac_min <- sum(a + ab + c + bc)
effect_ac <- mean(ac_plus) - mean(ac_min)
bc_plus <- sum(o + a + bc + abc)
bc_min <- sum(b + ab + c + ac)
effect_bc <- mean(bc_plus) - mean(bc_min)
abc_plus <- sum(abc + c + b + a)
abc_min <- sum(bc + ac + ab + o)
effect_abc <- mean(abc_plus) - mean(abc_min)
